### ISSUE TITLE
Prints the same graph for any repo

### ISSUE THREAD

**Issue by yonas** [MintArchit/gh-contribs#1]
`gh contribs` prints the same graph for any Github repo I've checked out

`gh extension install mintarchit/gh-contribs` ran today.
gh version 2.20.2 (2023-02-10)
OS: FreeBSD 13.1

**Comment by MintArchit** [comment]
At the moment, `gh-contribs` always outputs the graph for your whole Github account 
as it appears on your profile page.

I'll put `isolated per-repo graph` on the to-do list as a potential feature. 

Moreover, I welcome any pull requests or contributions.

**Comment by yonas** [comment]
@MintArchit Thanks.
