### ISSUE TITLE
Show legend, month, and contribution count

### ISSUE THREAD

**Issue by rollingmoai** [MintArchit/gh-contribs#2]
**Is your feature request related to a problem? Please describe.**
See https://github.com/Ryu0118/Kusa:
![image](https://user-images.githubusercontent.com/75471378/219593419-4d456642-b53f-4872-881b-0d9e2f3124d4.png)

**Describe the solution you'd like**
Show legend, month, and contribution count—separate flags for each.

**Describe alternatives you've considered**

**Additional context**

**Comment by MintArchit** [comment]
`Show legend, month, and contribution count—separate flags for each` added to the `todo` list

Any contributions or pull requests are appreciated.

**Comment by Ativerc** [comment]
Has the contribution count feature been added yet? If not, I would like to take it up. 
Will help to brush up on my shell scripting skills.

No promises on the timeline though.

**Comment by MintArchit** [comment]
Hi all, @rollingmoai, @Ativerc,
Up until now, i have not found any time to add these features.
I will seperate this issue now into three smaller feature issues including an implementation idea for each, 
open for everyone to implement:

- https://github.com/MintArchit/gh-contribs/issues/7#issue-2760083777
- https://github.com/MintArchit/gh-contribs/issues/9#issue-2760123020
- https://github.com/MintArchit/gh-contribs/issues/8#issue-2760097405
