### ISSUE TITLE
Exit code > 0 on `gh contrib`

### ISSUE THREAD

**Issue by tony-sol** [MintArchit/gh-contribs#3]
**Describe the bug**
Exit code > 0 on `gh contrib` but 0 if calling with `-D` flag

**To Reproduce**
1. Exec `gh contrib; echo $?`, see 1

**Expected behavior**

**Screenshots**
<img width="246" alt="Снимок экрана 2023-02-17 в 17 06 30" src="https://user-images.githubusercontent.com/33671815/219677430-788d947d-6946-443b-bcd7-c9f20379dba4.png">

**Desktop (please complete the following information):**
 - OS: macos 
 - Terminal wezterm+tmux
 - Font: JetBrains Mono Nerd Font
 - Version 

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS8.1, android13]
 - Terminal [e.g. termux, gnome-terminal, kitty]
 - Version
```~/.local/share/gh/extensions/gh-contribs [main] ✔ $ git status
On branch main
Your branch is up to date with 'origin/main'.
```

**Comment by MintArchit** [comment]
Fixed.

Thanks for the issue!

**Comment by tony-sol** [comment]
Thanks for quick response!
Works awesome!
